# Generated by Django 4.2.16 on 2024-12-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyFish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_bought", models.DateField(blank=True, null=True)),
                ("store", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "ph_min",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                (
                    "ph_max",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                (
                    "temp_min",
                    models.DecimalField(decimal_places=2, max_digits=2, null=True),
                ),
                (
                    "temp_max",
                    models.DecimalField(decimal_places=2, max_digits=2, null=True),
                ),
                ("schools", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField(null=True)),
                ("width", models.PositiveIntegerField(null=True)),
                ("height", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TankTransferHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("fishes", models.ManyToManyField(to="fish.myfish")),
                (
                    "tank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fish.tank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TankLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "tank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fish.tank",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myfish",
            name="species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fish.species",
            ),
        ),
    ]
