# Generated by Django 4.2.16 on 2024-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="temp_max",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="temp_min",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
