# Generated by Django 4.2.16 on 2024-12-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0002_alter_species_temp_max_alter_species_temp_min"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name_plural": "Species"},
        ),
        migrations.AddField(
            model_name="species",
            name="recommended_tank",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
