# Generated by Django 4.2.16 on 2024-12-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0004_alter_species_options_species_adult_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myfish",
            options={
                "ordering": ["name", "species__name"],
                "verbose_name_plural": "My Fishes",
            },
        ),
        migrations.AlterModelOptions(
            name="tank",
            options={"ordering": ["capacity"]},
        ),
        migrations.AddField(
            model_name="myfish",
            name="current_tank",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="fish.tank"
            ),
        ),
        migrations.AlterField(
            model_name="tank",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tank",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tank",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
