# Generated by Django 4.2.16 on 2024-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0006_tank_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tank",
            name="unit",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Liter"), (2, "Gallon")], default=2
            ),
        ),
    ]
