# Generated by Django 4.2.16 on 2024-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0007_alter_tank_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tanktransferhistory",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
