# Generated by Django 4.2.16 on 2024-12-13 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0008_alter_tanktransferhistory_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tanktransferhistory",
            name="fishes",
        ),
        migrations.AddField(
            model_name="tanktransferhistory",
            name="fish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fish.myfish",
            ),
        ),
    ]
