# Generated by Django 4.2.16 on 2024-12-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0009_remove_tanktransferhistory_fishes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tanktransferhistory",
            options={
                "ordering": ["date", "tank", "fish"],
                "verbose_name_plural": "Transer History",
            },
        ),
        migrations.AlterField(
            model_name="tanktransferhistory",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
