# Generated by Django 4.2.16 on 2024-12-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0010_alter_tanktransferhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tanktransferhistory",
            options={"ordering": ["date"], "verbose_name_plural": "Transer History"},
        ),
        migrations.AddField(
            model_name="tank",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
