# Generated by Django 4.2.16 on 2024-12-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0011_alter_tanktransferhistory_options_tank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfish",
            name="is_deceased",
            field=models.BooleanField(default=False),
        ),
    ]
