# Generated by Django 4.2.16 on 2024-12-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0012_myfish_is_deceased"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="species_files/"),
        ),
        migrations.AlterField(
            model_name="species",
            name="adult_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="ph_max",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="ph_min",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="temp_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="temp_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
