# Generated by Django 4.2.16 on 2024-12-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0013_species_photo_alter_species_adult_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="species_files/"),
        ),
    ]
